import { Sora } from 'next/font/google'
import './globals.css'
import TopLeftImg from './components/TopLeftImg/TopLeftImg'
import Nav from './components/Nav/Nav'
import Header from './components/Header/Header'


// font settings
const sora = Sora({ 
  subsets: ['latin'],
  variable: '--font-sora',\
  weight: ['100','200','300','400','500','600','700','800',] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <div className= ` page bg-site text-white bg-cover bg-no-repeat relative ${sora.variable} font-sora ` >
          <TopLeftImg />
          <Nav />
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
