import { Sora } from 'next/font/google'
import './globals.css'


// font settings
const sora = Sora({ 
  subsets: ['latin'],
  variable: '--font-sora',\
  weight: ['100','200','300','400','500','600','700','800',] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>{children}</body>
    </html>
  )
}
